services:
  postgres_db:
    container_name: postgres_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-dev}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-abcd1234}
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - common
    restart: unless-stopped

  be_api:
    container_name: 'be_api'
    hostname: 'be_api'
    image: 'huynhdn/nest-postgres-boilerplate:1.0'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # env_file: ".env"
    depends_on:
      - postgres_db

networks:
  common: